### ISSUE TITLE
Make it possible to get the end position of a node

### ISSUE THREAD

**Issue by djahandarie** [RazrFalcon/roxmltree#10]
Right now there is the `Node::pos()` method which gets you the start position of the node, but there seems to be no way to get the end position. This makes it impossible to get the original XML which corresponded to the node.

Looking at `xmlparser`, it seems like [`StrSpan`](https://docs.rs/xmlparser/0.8.1/xmlparser/struct.StrSpan.html) does include the end position. However it is probably not as easy as just using that, since most `StrSpan`s probably made available during parsing only cover the tag itself, not the entire element. I suspect it might be necessary to do something around [the `roxmltree` `ElementEnd` processing](https://docs.rs/roxmltree/0.4.1/src/roxmltree/parse.rs.html#344) too.

**Comment by djahandarie** [comment]
Thanks for the quick response!

> I'm not sure why do you want this.

Because I want to directly show the user the XML. Pretty-printing the node would also work, but that seemed like a harder task unless I'm missing some utility.

> Do you want just <text> or the whole string?

Yeah, I would want the entire string.

> Basically, you have to take node's next sibling, which will contain the end of the previous node.

I considered doing this, but was not sure how to handle the case where the node is the last child.

**Comment by RazrFalcon** [comment]
>was not sure how to handle the case where the node is the last child

The end of the string? But it will also include trailing spaces and newlines.

So yes, this is your only choice, since `xmlparser` is pull-based and doesn't know anything about the tree structure. So it can be done only on the `roxmltree` side.

I can add a shorthand, like `Node::len()`, if you want.

Also, pretty-printing will return a different text. Because of preprocessing.

**Comment by djahandarie** [comment]
> The end of the string? But it will also include trailing spaces and newlines.

I mean, if we have something like

```xml
<container>
  <a>1</a>
  <b>2</b>
</container>
```
I don't understand how I could get `<b>2</b>` from that, because taking to the end of the string would result in `</container>` being included as well. (Spaces and newlines would be easy to deal with, but not trailing tags).

> So yes, this is your only choice, since xmlparser is pull-based and doesn't know anything about the tree structure. So it can be done only on the roxmltree side.

I guess what I'm most confused about is why `roxmltree` can't just use `StrPos::end` when it's processing the `ElementEnd` that matches up with a given `ElementStart` (which I imagine `roxmltree` must be keeping track of to build its tree?).

**Comment by RazrFalcon** [comment]
Done. Feel free to ask any questions.
