### ISSUE TITLE
[N00b Question] Why use `Document::parse` instead of `Document::try_from`?

### ISSUE THREAD

**Issue by ds-ak** [RazrFalcon/roxmltree#107]
Please forgive my n00b question. `TryFrom` trait seems like a idiomatic rust alternative to `parse()`. I am just curious to learn why the author chose to do `parse()` instead? I am pretty sure this is a stupid question. Just asking it to fill my knowledge-gap. 

And apologies for asking a question in the issue. The discussion board was not enabled for this repo. Please feel free to close this issue without a response :sweat_smile:

**Comment by adamreichold** [comment]
`Document::parse` is most likely just older than stable access to the `TryFrom` trait.

More generally, consider that many types have `::new() -> Self` _and_ implement `Default`. The point is that having a specific method with specific name doing exactly what it says on the label is usually helpful. Traits on the other hand are required to work with these types "in generic context", i.e. when you want to construct values of a type `T` which is a generic parameter, you cannot just call `T::new()`, you have to specific a trait bound like `T: Default` to be able to call `T::default()`. So for this reason it is useful to additionally expose existing functionality via trait implementations so it can be used in generic context.

Returning to your question, my advice would be to use `Document::parse` when you know you are dealing with a `Document` and necessarily rely on traits like `TryFrom` when in generic context and you do not really care what `T` is as long as it can be fallibly constructed from a string, i.e. implements `TryFrom<&str>`.

**Comment by RazrFalcon** [comment]
>Document::parse is most likely just older than stable access to the TryFrom trait.

This. There were no `TryFrom` when this library was written.

Also, I don't think that `TryFrom` is idiomatic. Everyone doing whatever they want. Some use `new`, some `from_slice`/`from_str`, some `parse` and some probably `try_from`. There is no "right" way as far as I aware.

Also, the problem with `TryFrom` is that it doesn't take additional arguments. And we have to pass `ParsingOptions` somehow. And no, tuple is a hack.
