### ISSUE TITLE
Encoding gets messed up for CDATA

### ISSUE THREAD

**Issue by WhyNotHugo** [RazrFalcon/roxmltree#108]
This applies to master and not to 0.18.1.

Copy this into `src/lib.rs` and run `cargo test`:

```rs
#[test]
fn test_multi_get_parse_encoding_another() {
    let calendar_data = ExpandedName::from(("urn:ietf:params:xml:ns:caldav", "calendar-data"));

    let body = "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<C:calendar-data xmlns:C=\"urn:ietf:params:xml:ns:caldav\"><![CDATA[BEGIN(de baño)VCALENDAR\r\n]]></C:calendar-data>\n";
    assert!(body.contains("baño"));

    let body = std::str::from_utf8(body.as_ref()).unwrap();
    assert!(body.contains("baño"));

    let doc = Document::parse(body).unwrap();

    let raw_data = doc
        .descendants()
        .find(|node| node.tag_name() == calendar_data)
        .unwrap()
        .text()
        .unwrap();
    std::dbg!(&raw_data);
    assert!(raw_data.contains("baño"));
}
```

Basically this parses a string to a `roxmltree` and then reads the text from the cdata. `baño` turns into `baÃ±o` (that's why the `std::dbg!` is there).

**Comment by WhyNotHugo** [comment]
This regresses in 4f3566bcb919f63af6ad57e69bcbf7e03236968b.

**Comment by WhyNotHugo** [comment]
The issue is in `StringExt`. The way it pushes `u8` into `String` is not correct. Consider:

```rs
fn main() {
    let mut s = String::new();
    for c in String::from("baño").bytes() {
        s.push(c as char);
    }

    assert_eq!("baÃ±o", s);
}
````

**Comment by WhyNotHugo** [comment]
Converting individual bytes to characters and pushing those individually is not the same as pushing a single multi-byte character.

If I understand correctly, converting `u8` to `char` uses ISO-8859-1: https://doc.rust-lang.org/std/primitive.char.html#impl-From%3Cu8%3E-for-char

**Comment by RazrFalcon** [comment]
Ugh... my bad. Didn't thought about that.
