### ISSUE TITLE
Making the tokenizer public?

### ISSUE THREAD

**Issue by udoprog** [RazrFalcon/roxmltree#115]
Hi,

I currently use `xmlparser` for parsing a subset of xml and noticed that that project is discontinued. I'm also aware about the correctness in for example entity expansion which caused you to focus on this higher level crate rather than `xmlparser`.

That being said, I do make use of xmlparser to parse a stricter subset of xml, one which for example doesn't allow an arbitrary span of capabilities which is supported by entities enforced by a dtd. To this end I've been enjoying using your tokenizer and would like to continue working with that pattern.

Is there any chance you can make the tokenizer of this project public so I can keep using it and benefit from future changes or fixes?

**Comment by RazrFalcon** [comment]
Nope. The whole reason `xmlparser` become archived/deprecated is because I don't have interest and time in supporting such a use case. Your only option is to fork `xmlparser`.

**Comment by udoprog** [comment]
All right! Would you mind transferring the `xmlparser` crate for me to maintain or would you prefer I fork it under a new name?

**Comment by RazrFalcon** [comment]
A hard fork would probably be too much, so I've added you as an owner to the github repo + crates.io

**Comment by udoprog** [comment]
Thank you for being awesome!

**Comment by RazrFalcon** [comment]
No problem 😄
