### ISSUE TITLE
UnknownEntityReference for HTML entities

### ISSUE THREAD

**Issue by andrewbanchich** [RazrFalcon/roxmltree#12]
Great work! Thank you for building this.

I am trying to parse XML that contains HTML entities like `&prime;`, but I am getting:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UnknownEntityReference("prime", TextPos { row: 450, col: 3724 })', src/libcore/result.rs:997:5
```

Is there any way in particule you'd recommend I handle this?

**Comment by RazrFalcon** [comment]
>XML that contains HTML entities like `&prime;`

It's not a valid XML.

Here is `lxml` output:

```
<e>&prime</e>
```

**Comment by andrewbanchich** [comment]
Yeah, I thought that could be the issue. Is there any way to hook into your crate to say "if there's this error then just treat it like a string"?

**Comment by RazrFalcon** [comment]
No. You should fix you XML. If you can modify it, than just add this to the top:

```
<!DOCTYPE name [
    <!ENTITY prime '′'>
]>
```

We can't ignore invalid entities, because it may lead to other errors.

**Comment by andrewbanchich** [comment]
Okay, thank you!
