### ISSUE TITLE
Error parsing XML with unknown entity reference in &copy

### ISSUE THREAD

**Issue by szy1231** [RazrFalcon/roxmltree#122]
I encountered an error while parsing an XML document using the "roxmltree" library. The error message is as follows:
`UnknownEntityReference("copy", TextPos { row: 5, col: 41 })`

The XML content that caused the error is:
```
<note>
  <to>Tove &amp; Family</to>
  <from>Jani &lt;The Friend&gt;</from>
  <heading>Reminder</heading>
  <body>Don't forget me this weekend! &copy; 2023</body>
</note>
```

**Comment by RazrFalcon** [comment]
`&copy;` is part of HTML, not XML. That's why you're getting an error.
