### ISSUE TITLE
Maintenance help

### ISSUE THREAD

**Issue by RazrFalcon** [RazrFalcon/roxmltree#123]
@adamreichold Me again. Would you be interested in maintaining this repo?
As you can see, the project is effectively done, so unless some major issues would arise there is no need to do anything with it. I just want to have someone as a backup in case I would not be able to access it anymore.

**Comment by adamreichold** [comment]
The answer is the same as for `memmap2`, I am stretched but if the alternative is to archive, I will try to keep the lights on as I depend on this crate. It should be better here, since it is somewhat central at my current `$DAYJOB`, so I should be able to direct work time towards its maintenance.

**Comment by RazrFalcon** [comment]
Thanks! I doubt you would need to worry about it. 1 commit per year would be enough 😄
