### ISSUE TITLE
Get Entity from text

### ISSUE THREAD

**Issue by asafigan** [RazrFalcon/roxmltree#13]
I would like to get the Entity code from a text node. I am parsing an xml document that describes a dictionary. It uses Entities for all of the parts of speech. I would like to get both the full text ("adjective") and the code ("adj"). Is this possible to add as an api to node or is there another way to get this information?

**Comment by RazrFalcon** [comment]
Can you provide an XML example?

**Comment by asafigan** [comment]
Yes, I am parsing the english version of [The JMDict Project](https://www.edrdg.org/jmdict/j_jmdict.html) (follow the like find all the data sources).

**Comment by RazrFalcon** [comment]
So you want to get `<pos>&unc;</pos>` instead of `<pos>unclassified</pos>`? It's not possible.

**Comment by asafigan** [comment]
Ok, do you know of any tools/packages that will parse the Entity declarations for me so that I can translate them back?

**Comment by RazrFalcon** [comment]
I'm not sure what you are trying to achieve, but you can try [xmlparser](https://github.com/RazrFalcon/xmlparser), which is used by roxmltree itself.

**Comment by asafigan** [comment]
Ok, Thanks that is exactly what I needed. I just want I standard abbreviation for each part of speech without having to hard code them. Using the Entity name is the easiest way to do this.

**Comment by RazrFalcon** [comment]
Ok. Then I'm closing this issue.
