### ISSUE TITLE
Performance comparison with RapidXML

### ISSUE THREAD

**Issue by erszcz** [RazrFalcon/roxmltree#14]
Would you care to add RapidXML to the benchmark?
It's a C++ XML parser, arguably a very fast one. Rust has a safety advantage over C++, but both languages target a similar niche - it would be awesome if apart from safety the Rust library also offered similar (or better!) performance.

http://rapidxml.sourceforge.net/
https://github.com/dwd/rapidxml - one of multiple GitHub mirrors

**Comment by RazrFalcon** [comment]
roxmltree isn't that fast, really. There are notes in the [Performance](https://github.com/RazrFalcon/roxmltree#performance) section, explaining why we do not have a proper benchmarks.

Afaik, RapidXML doesn't support namespaces, and this is the whole point of roxmltree.

Basically, benchmarks are hard and time consuming. If someone will do them - that's will be great. The current one are just to show that roxmltree is faster that other Rust libraries.
