### ISSUE TITLE
Namespaced Tags

### ISSUE THREAD

**Issue by daaku** [RazrFalcon/roxmltree#15]
This is a stripped down version of a file which seems like it should work (does with `quick-xml` in any case which is what I'm currently using):

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?mso-application progid="Excel.Sheet"?>

<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet">
<Worksheet>
	<ss:Table>
		<Row>
			<Cell>
				<Data>Hello</Data>
			</Cell>
		</Row>
	</ss:Table>
</Worksheet>
</Workbook>
```

To see the failure in action:

```sh
> cargo run --example ast -- sample.xls
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
     Running `target/debug/examples/ast sample.xls`
Error: expected 'Table' tag, not 'ss:Table' at 12:2.
```

**Comment by RazrFalcon** [comment]
Thank! That's an interesting bug. It fails because of duplicated namespaces. It chouses the default namespace first, which doesn't have a `ss` prefix. `lxml` works fine, so it's a `roxmltree` bug.

`quick-xml` works fine, because it doesn't support namespaces.

**Comment by daaku** [comment]
Sweet, thanks for the quick fix and release. It works for me now.
