### ISSUE TITLE
Multiple entities in the same text node are misinterpreted as entity loop/nesting

### ISSUE THREAD

**Issue by pwlodarczyk92** [RazrFalcon/roxmltree#19]
Because the entity loops are detected inaccurately, the example below panics, even though there's no loop or no nesting of the entity definitions. Modification of the depth limit would be a nice workaround but that's not possible right now.
```
fn main() {
    let sample = r#"<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE patent [<!ENTITY plus "+">]>
<PATDOC>
&plus;&plus;&plus;&plus;&plus;&plus;&plus;&plus;&plus;&plus;&plus;&plus;
</PATDOC>
"#;
    roxmltree::Document::parse(sample).unwrap();
}
```

**Comment by RazrFalcon** [comment]
Yes, this is an expected behavior. Do you have a real-world file with such structure?

**Comment by pwlodarczyk92** [comment]
Yes, some of the patents granted by USPTO in years ~2002-2004 have this structure. As an example, patent no. D0497559 ([pg041026.zip](https://bulkdata.uspto.gov/data/patent/grant/redbook/fulltext/2004/)) looks like this:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE PATDOC SYSTEM "ST32-US-Grant-025xml.dtd" [
<!ENTITY USD0497559-20041026-D00000.TIF SYSTEM "USD0497559-20041026-D00000.TIF" NDATA TIF>
<!ENTITY USD0497559-20041026-D00001.TIF SYSTEM "USD0497559-20041026-D00001.TIF" NDATA TIF>
<!ENTITY USD0497559-20041026-D00002.TIF SYSTEM "USD0497559-20041026-D00002.TIF" NDATA TIF>
<!ENTITY USD0497559-20041026-D00003.TIF SYSTEM "USD0497559-20041026-D00003.TIF" NDATA TIF>
]>
<PATDOC DTD="2.5" STATUS="Build 20031001">
<SDOBI>
<B100>
...
<B562><NCIT><STEXT><PDAT>(a) &ldquo;Little Wizard Security Detector&rdquo;, (b) &ldquo;Lumber Wizard&rdquo;, (c) &ldquo;Wood Scan Wizard&rdquo;, (d) &ldquo;Wall Wizard Stud Finder&rdquo;, (e) &ldquo;Sprinkler Head Detector&rdquo;, (f) &ldquo;Experiment Wizard&rdquo;, (g) &ldquo;Wizard Vib-Probe Pinpointers&rdquo;, (h) &ldquo;Wizard Walk N Seek&rdquo;, (i) &ldquo;Security Products Flyer&rdquo;, (j) &ldquo;Little Wizard Security De&rdquo;, (k) &ldquo;Security Wizard&rdquo;, (l) &ldquo;Wizard Mail and Package Scan&rdquo;, and (m) &ldquo;Wizard SHOTfinder&rdquo;, as disclosed on http://wizarddetectors.com/flyers.cfm, Wizard Industries online brochure pages downloaded Feb. 4, 2002, Jul., 1998, copyright 1998-2001 (3 pgs.). </PDAT></STEXT></NCIT><CITED-BY-OTHER/></B562>
...
```
There's enough quotation marks injected as entities in the last line to exceed the limit. You can find more information about the structure of the xml's [here](https://www.uspto.gov/learning-and-resources/xml-resources).

The entity declarations are not present in that xml but have to be included somehow. I planned to inject them myself by raw string manipulations similarly to the solution proposed [in the previous issue](https://github.com/RazrFalcon/roxmltree/issues/12), and I stumbled on the problem above while implementing that solution.

**Comment by RazrFalcon** [comment]
Done. Please test it out.

**Comment by pwlodarczyk92** [comment]
Everything works now, thank you for your work and the quick reply :)
