### ISSUE TITLE
Huge memory hog

### ISSUE THREAD

**Issue by npajkovsky** [RazrFalcon/roxmltree#25]
Hello,

I'm trying to use the library for parsing medium size xml, but some of them are gigantic, like this one

   https://vdp.cuzk.cz/vymenny_format/soucasna/20200331_OB_554782_UZSZ.xml.zip

Uzipped xml file is about 982M 20200331_OB_554782_UZSZ.xml.

Now, when you try to run e.g. stats example, it will eat your whole memory, then swap and it will so so finish on my MacBook Pro 2018 16GB ram.

**Comment by RazrFalcon** [comment]
You should use zero allocation parsers, like [xmlparser](https://github.com/RazrFalcon/xmlparser) for large files.

On the other hand, `roxmltree` should usually use less memory that the input data. Look like your file bloats the memory with namespaces.

I will see what can be done.

**Comment by npajkovsky** [comment]
> You should use zero allocation parsers, like [xmlparser](https://github.com/RazrFalcon/xmlparser) for large files.

Thanks for pointing to that. I'll look at it.

> On the other hand, `roxmltree` should usually use less memory that the input data. Look like your file bloats the memory with namespaces.

When I print AST, it basically prints namespaces over and over.

> I will see what can be done.

Thanks.

**Comment by RazrFalcon** [comment]
>When I print AST, it basically prints namespaces over and over.

Yes, right know `roxmltree` resolves namespaces for each node, which is way too expensive for files like this. On the other hand, it makes querying faster. Will see.

**Comment by npajkovsky** [comment]
> > When I print AST, it basically prints namespaces over and over.
> 
> Yes, right know `roxmltree` resolves namespaces for each node, which is way too expensive for files like this. On the other hand, it makes querying faster. Will see.

What do you mean by "query xml"? Can you give me example of simple query? I cannot recall, that I found any word about query in doc :-/

**Comment by RazrFalcon** [comment]
I meant the `Node`'s API.

**Comment by RazrFalcon** [comment]
In the latest master the memory usage have reduced significantly thanks to @tomjw64. It still uses 7.5GiB. which is 7.5 times bigger than the input file, but it should be good for now. 

Feel free to reopen this issue if you think that this is not enought.
