### ISSUE TITLE
parsing XML characters

### ISSUE THREAD

**Issue by jdrouet** [RazrFalcon/roxmltree#33]
Hi!

I'm trying to parse the following:
```xml
<span>
&copy; Croft's Accountants Inc., All Rights Reserved.
</span>
```
And I end up with the following error: `UnknownEntityReference("copy", TextPos {...})`

Are the XML and HTML not handled? Can't I have them as a String?

**Comment by RazrFalcon** [comment]
This is an HTML reference. `roxmltree` is purely and XML parser.

**Comment by jdrouet** [comment]
So shouldn't it be considered as a string?

**Comment by RazrFalcon** [comment]
No, this is a malformed XML. 

You can test it here: https://www.w3schools.com/xml/xml_validator.asp
