### ISSUE TITLE
Rust Lifetimes: Is it possible to have roxmltree take ownership of the text string?

### ISSUE THREAD

**Issue by bergkvist** [RazrFalcon/roxmltree#34]
## A minimal example

```rust
use std::path::PathBuf;
use roxmltree;

fn main() {
  let filepaths: Vec<&PathBuf> = get_filepaths();

  filepaths.iter()
    .map(std::fs::read_to_string)
    .map(|text| roxmltree::Document::parse(&text.unwrap()))
    .for_each(|tree| {
      // Do something with each XML tree
    })
}
```

When I try to compile:
```rust
error[E0515]: cannot return value referencing temporary value
  --> src\main.rs:32:21
   |
32 |         .map(|text| roxmltree::Document::parse(&text.unwrap()))
   |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^-------------^
   |                     |                           |
   |                     |                           temporary value created here
   |                     returns a value referencing data owned by the current function
```

**Comment by RazrFalcon** [comment]
No, roxmltre doesn't store the input text.

**Comment by bergkvist** [comment]
Based on the code above, how would you have modified the code to fix this error?

Create a wrapper struct that contains both the string and the roxmltree document?

**Comment by RazrFalcon** [comment]
Just use a simple `for` loop.

>Create a wrapper struct that contains both the string and the roxmltree document?

Rust doesn't support self-referential structs.

**Comment by bergkvist** [comment]
The problem with using a for-loop is that I want to switch out .iter() with .par_iter() (from the rayon crate) for parsing xml-files in parallel. 

I want to parse thousands of xml files as quickly as possible - so I imagine splitting the parsing across multiple cores might help.

**Comment by RazrFalcon** [comment]
Then you should load a font inside a closure:

```rust
let files = ["benches/fonts.conf", "benches/large.plist", "benches/medium.svg"];
let results: Vec<_> = files.into_par_iter()
    .filter_map(|file| {
        let text = std::fs::read_to_string(file).ok()?;
        let doc = roxmltree::Document::parse(&text).ok()?;
        Some(doc.descendants().count())
    })
    .collect();

dbg!(results);
```

```
[examples/ast.rs:20] results = [
    33,
    22876,
    1136,
]
```

**Comment by bergkvist** [comment]
Yeah, keeping everything inside the same close works! Thanks

What do you mean when you write "Prefer memmap for maximum performance"?

**Comment by RazrFalcon** [comment]
https://docs.rs/memmap/0.7.0/memmap/struct.Mmap.html
