### ISSUE TITLE
no_std Support

### ISSUE THREAD

**Issue by Darneas** [RazrFalcon/roxmltree#38]
Dear all,

as roxmltree only depends on [xmlparser](https://crates.io/crates/xmlparser), would it be possible to make roxmltree support no_std environments?

xmlparser is no_std ready, so that would already take some effort away.

Best regards,
Andreas

**Comment by RazrFalcon** [comment]
It's not possible, because `roxmltree` allocates. We can do no_str + alloc, but I don't see a point in it.

**Comment by DemiMarie** [comment]
@RazrFalcon Wasm is `no_std` and has full support for `alloc`.  I’d be willing to make a PR if you were interested.

**Comment by RazrFalcon** [comment]
I haven't worked with wasm, so I'm not sure. But if this is something you're interested in, I will accept the patch.
I just want to avoid unnecessary restrictions. And no_std is one of them.

**Comment by DemiMarie** [comment]
I understand not wanting to restrict yourself.  As long as `roxmltree` uses neither I/O nor threads, it should be fine with `alloc`.

**Comment by RazrFalcon** [comment]
The no_std+alloc support have been added.
