### ISSUE TITLE
Debug is not implemented for iterator structs

### ISSUE THREAD

**Issue by 5225225** [RazrFalcon/roxmltree#39]
I have the code

```rust
use roxmltree::NodeType;

let doc = roxmltree::Document::parse(input)?;

let channel = doc.root().children().filter(|x| x.node_type() == NodeType::Element).exactly_one().unwrap();
```

Where exactly_one is [itertools::Itertools::exactly_one](https://docs.rs/itertools/0.9.0/itertools/trait.Itertools.html#method.exactly_one). The problem I'm getting is that I can't use .unwrap() on that since the error needs to implement Debug, which it only does if the inner iterator does, and [roxmltree::Children](https://docs.rs/roxmltree/0.13.0/roxmltree/struct.Children.html) doesn't.

It looks like just adding a `#[derive(Debug)]` to the iterator structs would be enough. Iterators generally don't have too useful of a debug output for end users, but it's important that they do implement Debug and output *something* otherwise the types are hard to work with.

I'd also add [the missing debug implementation lint](https://doc.rust-lang.org/rustc/lints/listing/allowed-by-default.html#missing-debug-implementations) to ensure all public types have a debug implementation, or at least it's intentional to not have one.

**Comment by RazrFalcon** [comment]
Yes, I guess we can add this. I've haven't done this for the same reason you've mentioned - there are just no useful into there.
