### ISSUE TITLE
.descendants() iterator not returning full descendants for nested nodes

### ISSUE THREAD

**Issue by hcgaron** [RazrFalcon/roxmltree#43]
I'm having an issue iterating over descendants of deeply nested nodes.  Calling `.descendants()` on a node at the top of the document is working fine, but when I query a node somewhere deeper in the doc and then try to call `.descendants()` on it, I am only getting partial results.

The data I'm using is not open source unfortunately, so I can't share here.  If you have test data I would be glad to provide a working example.

**Comment by RazrFalcon** [comment]
Well, I can't help you here. I need a reproducible example.

**Comment by hcgaron** [comment]
Sorry, as I worried it was user error. I believe I've sorted it. You can close. 

Sorry for bothering you. Thanks for this library, it's very helpful.

**Comment by RazrFalcon** [comment]
No problem.
