### ISSUE TITLE
TextPos on parsed tree

### ISSUE THREAD

**Issue by burrbull** [RazrFalcon/roxmltree#44]
The question is can I take text position of some node if parsing is successful?
For example if I need post-process the result and return custom error with position.

**Comment by RazrFalcon** [comment]
Yes. You should use [Node::range](https://docs.rs/roxmltree/0.14.1/roxmltree/struct.Node.html#method.range) first and then [Document::text_pos_at](https://docs.rs/roxmltree/0.14.1/roxmltree/struct.Document.html#method.text_pos_at).

See `examples/print_pos.rs`

**Comment by burrbull** [comment]
Thank you, I've not noticed this method.
