### ISSUE TITLE
[Q/A] What should be the return type of the function in print_pos.rs example?

### ISSUE THREAD

**Issue by mzfr** [RazrFalcon/roxmltree#46]
Hey, I am new to Rust so having a hard time figuring out what should be the return typeset if I want to send the `doc` back to the calling function.

```rust
fn read_xml(file_path: String){
	let text = std::fs::read_to_string(&afile_path).unwrap();
    let doc = match roxmltree::Document::parse(&text) {
        Ok(doc) => doc,
        Err(e) => {
            println!("Error: {}.", e);
            return;
        },
    };
	return doc;  // This gives error about not setting a proper return type
}

fn main() {
	read_xml("myxml.xml");
}
```

I tried doing something like:

```rust
fn read_xml(file_path: String) -> roxmltree::Document<'static>{
```

but then I get an error on the `return;` in the `Err(e)`.

Now I want to know what should be the return type of `read_xml` function and how should I accept it in `main` function. 

Thanks

**Comment by RazrFalcon** [comment]
This is because your first `return` returns `()`/void, second returns `roxmltree::Document` and the functions itself returns `()`.

You can't actually return `Document` because of lifetimes. `doc` must outlive `text`. 

I think you want:

```rust
fn read_xml(text: &str) -> Result<roxmltree::Document, roxmltree::Error> {
    roxmltree::Document::parse(text)
}

fn main() {
    let text = std::fs::read_to_string("myxml.xml").unwrap();
    let doc = read_xml(&text).unwrap();
}
```

or just 

```rust
fn main() {
    let text = std::fs::read_to_string("myxml.xml").unwrap();
    let doc = roxmltree::Document::parse(text).unwrap();
}
```

**Comment by mzfr** [comment]
@RazrFalcon ok I see that there is this lifetimes thing. I understand it now, coming from python I'm kind of used to returning anything I want whenever I want 😅 

Thanks for answering :)
