### ISSUE TITLE
HTML parsing

### ISSUE THREAD

**Issue by vityafx** [RazrFalcon/roxmltree#5]
I am parsing an invalid HTML code and so I have `UnexpectedCloseError` very often. Currently there is no way to deal with it - the library just stops from working and that's it. I'd, however, ignore these errors and continue parsing the XML further. Is it possible?

**Comment by RazrFalcon** [comment]
HTML is a totally different beast. You should you a dedicated HTML parser instead.

**Comment by vityafx** [comment]
Yes, but valid HTML code must be valid CODE code. So it must be pretty okay to parse html with xml parser, just not invalid one. I know of some libraries for Java & C++ which do not stop from working if they C invalid XML, they somehow continue working with it. Can we do the same? Just some flag, probably, in parser builder that we can set for ignoring such errors? Like

```rust
let parser = XmlParser::new().ignore_unclosed_tags(true).build();
```

**Comment by vityafx** [comment]
Okay, I was wrong. But it is very sad if you don't want to at least suppress some warnings (errors in this case) as you disallow many people from using the library. It also would be more flexible as we could still parse xml (in particularly this case - xml-like) data. Of course, anyone can reinvent his own wheels. I do not ask to support HTML data, I ask about suppressing some errors during the parsing. Browsers can interpret invalid xml data, why can't we? If it is simply not possibly by the library structure, just say so.

**Comment by RazrFalcon** [comment]
>I ask about suppressing some errors during the parsing

It's not just one error. There are a lot of differences.

>Browsers can interpret invalid xml data, why can't we?

Because it's an XML parser, not HTML one.

>If it is simply not possibly by the library structure, just say so.

I have zero knowledge about HTML, that's why I'm not planning to support it.

Just use [html5ever](https://github.com/servo/html5ever).

**Comment by vityafx** [comment]
Well, probably you are right and xml must be strict in that as it must be a correct tree. Thank you for your response.
