### ISSUE TITLE
Parsing special characters

### ISSUE THREAD

**Issue by DocKDE** [RazrFalcon/roxmltree#53]
Hi,
I'm pulling a folder structure from a WebDAV server and try to parse the results with roxmltree. This is the snippet I use for it:
```
    let doc = roxmltree::Document::parse(&body).unwrap();
    let paths: Vec<&str> = doc
        .descendants()
        .filter(|n| n.has_tag_name("href"))
        .map(|n| n.text().unwrap())
        .collect();

    for i in paths {
        println!("{:#?}", i)
    }
```
As you can see, I'm interested in the text of the `href` tags. Since these contain several special characters like spaces and such the resulting strings look something like this:  `World%c2%b4s%20best%20Chocolate%20Chip%20Cookies/`
Does roxmltree provide anything for parsing this into the actual plain text names or do I have to take care of this myself?
Best

**Comment by RazrFalcon** [comment]
You should use [data-url](https://github.com/servo/rust-url/tree/master/data-url) or [percent_encoding](https://github.com/servo/rust-url/tree/master/percent_encoding). XML doesn't know anything about it.
