### ISSUE TITLE
[Feature] Add a way to validate XML with custom "rules"

### ISSUE THREAD

**Issue by alexmozaidze** [RazrFalcon/roxmltree#55]
I am making data-driven scripting for my game with XML, and it would be cool if I could specify what certain documents should look like. Like, for instance, restrict document to only having specified tags, or that a tag can only have specified attributes (some of which can be optional).
Edit: Maybe add an option to `ParsingOptions` for that, possibly?

**Comment by RazrFalcon** [comment]
You basically need a XML schema and roxmltree doesn't provide it. It's strictly a parser.
