### ISSUE TITLE
Serde support

### ISSUE THREAD

**Issue by adamreichold** [RazrFalcon/roxmltree#59]
This is more of a request for comments than an issue: I consume an XML-based API where neither quick-xml's Serde support the strong-xml or hard-xml wrapper around xmlparser can currently handle the format (OGC CSW records). serde-xml-rs does correctly deserialize the format though.

While I understand that one would normally base Serde support directly on xmlparser instead of roxmltree, in my case, my data model is already Serde-oriented and going via the intermediate roxmltree is still ten times (90%) faster than using serde-xml-rs and it seems significantly simpler to implement than an integration with xmlparser. (So basically, I just use Serde to avoid manually unpacking the document structure.)

Hence, I created a small crate available at https://github.com/adamreichold/serde-roxmltree and wanted to ask you a few questions before publishing anything, namely:
* Whether you are alright with name directly referencing roxmltree or whether I should try to be more creative?
* Whether you consider this useful and small enough to include here as an optional feature? (It works equally well as a separate library, so I think this would mainly help discoverability.)
* Whether you have any hints on things that should be implemented differently?

**Comment by RazrFalcon** [comment]
>While I understand that one would normally base Serde support directly on xmlparser instead of roxmltree

Not really. `xmlparser` is just a tokenizer/lexer. You cannot use it directly to handle real-world XML. `roxmltree` adds proper escaping/attribute value normalization, entity references, whitespaces and namespaces.

As for serde, I have essentially zero knowledge about it, at least from the implementation and not a user perspective.
Adding `serde` feature directly to `roxmltree` seems like an unnecessary maintenance burden for me. So I would prefer a separate repo/crate for now. And when it would become stable and battle-tested we might merge it here.
At a quick glance, `serde-roxmltree` looks way too minimalistic. Imho, XML is too complex/versatile for `serde`. You do not handle namespaces, complex text (text can be before and after an element) and so on.

Like for example, how would you handle:

```xml
<text>some<q/>text</text>
```

So yes, _directly referencing roxmltree_ if fine. Separate crate for now. No comments about the implementation.

**Comment by adamreichold** [comment]
> Imho, XML is too complex/versatile for serde. You do not handle namespaces, complex text (text can be before and after an element) and so on.

Indeed, I think this is a general issue with all integrations between Serde and XML. One can try to work around this by giving special meaning to names given via `#[serde(rename = "..")]`, but I suspect this would quickly spiral into a separate mini-language. I think this is also why crates like strong-xml/hard-xml go for a separate `XmlRead` trait and derive macros which include fine-control over the mapping to the XML structure.

In any case, the trivial mapping to children and attributes which ignores namespaces is often good enough for the applications I have and one can always fall back to using `Document/Node` directly when that does not work.

> So yes, directly referencing roxmltree if fine. Separate crate for now. No comments about the implementation.

Thanks for looking it and giving clear advice!
