### ISSUE TITLE
[Feature Request] Parallelized descendents iterator

### ISSUE THREAD

**Issue by GrayJack** [RazrFalcon/roxmltree#6]
Would be possible, or more like it, would be beneficial to create a `par_descendents()` method that returns a parallel iterator?

**Comment by RazrFalcon** [comment]
Parallel in what sense?

**Comment by GrayJack** [comment]
Like rayon `par_iter()` iterators

**Comment by RazrFalcon** [comment]
Can you provide a use case for this?

**Comment by GrayJack** [comment]
Maybe to use the power of multi core processors, since it's read only, we would benefit to filter or map as we parallelize the process

**Comment by RazrFalcon** [comment]
I'm not sure that it can provide any benefits. 

Anyway, I have zero knowledge about Rust's threading story, so I can't implement it anyway. Probably it should be done as separate crate, if someone will be interested in it.
