### ISSUE TITLE
question: is there a pure iterator pattern for very large files?

### ISSUE THREAD

**Issue by cottrell** [RazrFalcon/roxmltree#62]
Hitting

    Error: the input string should be smaller than 4GiB.

reading through the code not sure if there is an easy pattern to work with large files as I *think* it relies on finding both start and end tags for each node, but only had a cursory look so far.

**Comment by RazrFalcon** [comment]
Yes, this is an artificial limitation. We use `u32` for token spans. If we switch to `usize`/`u64` this will increase the total memory usage.

The only way to avoid this limitation is by disabling token spans altogether, which is currently not possible.

See #25 and https://github.com/RazrFalcon/roxmltree/commit/5e5a98b4274a4aa856505c7dccda0a3dc0e6038c


You try using `xmlparser` crate directly, but it's pretty low-level.
