### ISSUE TITLE
Reduce peak memory usage

### ISSUE THREAD

**Issue by RazrFalcon** [RazrFalcon/roxmltree#63]
Measure and try to reduce the peak memory overhead over the input file. Basically find out how much memory is used by roxmltree metadata itself.

- [x] Make token ranges optional
- [x] Try removing `ExpandedNameOwned::prefix`
- [x] Remove 4GB input limit
- [ ] ~~Try using custom `ShortRange` for attributes and namespaces indexes. Like 20.12 packed in u32~~
- [x] Test peak memory usage

**Comment by tomjw64** [comment]
:eyes:

**Comment by tomjw64** [comment]
👀 I'll spend a few hours on this.

**Comment by RazrFalcon** [comment]
@tomjw64 Thanks. Removing `ExpandedNameOwned::prefix` is the most important one. It's just garbage. But would require some changes to the parser.

A custom `ShortRange` a bit more tricky. I will probably look into it myself.

**Comment by RazrFalcon** [comment]
Token ranges are surprisingly not that memory-heavy. On the 1GB XML from #18 they produce about 5% memory overhead. They still should be optimized though.
