### ISSUE TITLE
Perform attributes normalization on access

### ISSUE THREAD

**Issue by RazrFalcon** [RazrFalcon/roxmltree#65]
[Attributes normalization](https://www.w3.org/TR/xml/#AVNormalize) requires an allocation, which is both expensive to CPU and RAM. And it doesn't guarantee that such attribute will be accessed at all. Or accessed multiple times.
Therefore we could try performing normalization only on access. This would improve parsing performance and reduce memory usage by sacrificing attribute value access performance.

Also, it means we would have to return `Cow<'input, str>)` instead of `&'input str`. Which is meh...

And, a caller might not want to perform normalization to begin with. So this way we would be able to provide a raw access to an attribute value.

**Comment by adamreichold** [comment]
I look into this and from a first glance, the main problem seems to be that normalization is tied in with the `xmlparser` machinery which is not present at the time when `Document` is used to access the parsed representation. Furthermore, things like `LoopDetector` would need to be constructed on-demand instead once per parse which means they need to be cheap as their costs will not be amortized. (Or they have to be cached within `Document` leading to concurrency issues.)

**Comment by RazrFalcon** [comment]
Hm... you're right. 

My problem with the current approach is when parsing SVG, there are some files with huge paths (`<path d="..."/>`) or base64 encoded images. And as soon as one of them contains a new line - we have to normalize it, i.e. allocate. Which is just a waste of memory.

I think we could try doing entity resolving during parsing, but new lines to spaces conversion during access. Including an optional method to return a "raw", but with entities resolved, value.

**Comment by RazrFalcon** [comment]
Doesn't seems like there is a good way to do this.
