### ISSUE TITLE
Make it easier to get a TextPos from an error

### ISSUE THREAD

**Issue by cormacrelf** [RazrFalcon/roxmltree#7]
Hi, love your work on this, I'm using it to parse [CSL](https://citationstyles.org/) for a new citation processor and it's fantastic.

CSL is mostly written by hand and involves big enums of allowed attribute values, so it's important to point out when and where these mishaps happen. I use the `TextPos` embedded in each variant of `roxmltree::Error` to produce a [codespan](https://docs.rs/codespan/0.2.0/codespan/) for each error, and this works well.

However, it's probably better that this big match statement lives alongside its definition so other users can benefit and get the TextPos easily, and without having to update if `roxmltree` adds new variants. It would probably live on `impl Error`. Here is my source:

```rust
fn get_pos(e: &Error) -> TextPos {
    use xmlparser::Error as XP;
    match *e {
        Error::InvalidXmlPrefixUri(pos) => pos,
        Error::UnexpectedXmlUri(pos) => pos,
        Error::UnexpectedXmlnsUri(pos) => pos,
        Error::InvalidElementNamePrefix(pos) => pos,
        Error::DuplicatedNamespace(ref _name, pos) => pos,
        Error::UnexpectedCloseTag { pos, .. } => pos,
        Error::UnexpectedEntityCloseTag(pos) => pos,
        Error::UnknownEntityReference(ref _name, pos) => pos,
        Error::EntityReferenceLoop(pos) => pos,
        Error::DuplicatedAttribute(ref _name, pos) => pos,
        Error::ParserError(ref err) => match *err {
            XP::InvalidToken(_, pos, _) => pos,
            XP::UnexpectedToken(_, pos) => pos,
            XP::UnknownToken(pos) => pos,
        },
        _ => TextPos::new(1, 1)
    }
}
```

**Comment by RazrFalcon** [comment]
Thanks.

Maybe it will be better to extract the TextPos from the enum completely. So `Error` will became:

```rust
pub struct Error {
    pub kind: ErrorKind,
    pub pos: TextPos,
}
```

At the moment, I don't care about the `Error` itself, because I'm using it only to print the messages.

**Comment by cormacrelf** [comment]
I think that works well. If you wanted to give even more error printing control, it might also be good not to include the position in the Display implementation, because library consumers can just do `format!("{}, at {}", kind, pos)`. Eventually, errors in std will also have [the ability to track their causes](https://github.com/rust-lang/rust/issues/53487), so the cause could then be removed from the Display impl as well.

**Comment by RazrFalcon** [comment]
I think that this a very rare case. And as long as there is not an official/popular pattern for error handling I think I will stick with the current one.

**Comment by cormacrelf** [comment]
Fair enough.

**Comment by cormacrelf** [comment]
Great! Thank you.
