### ISSUE TITLE
[Feature request] Adding some selector (CSS or XPath) behind a feature gate

### ISSUE THREAD

**Issue by saona-raimundo** [RazrFalcon/roxmltree#70]
First of all, thanks for the crate!!

After using `roxmltree` for a while I was missing some handy way to traverse the tree. Then, I saw that there is a "companion" crate [`simplecss`](https://crates.io/crates/simplecss) that parses css selectors and exposes a corresponding traversal trait [`Element`](https://docs.rs/simplecss/0.2.1/simplecss/trait.Element.html) that structs represnting a node of a XML tree shall implement.

There is already the code in the [`examples` of `simplecss`](https://github.com/RazrFalcon/simplecss/blob/master/examples/select.rs).

## Request

Would you consider adding the implementation of [`Element`](https://docs.rs/simplecss/0.2.1/simplecss/trait.Element.html) for [`roxmltree::Node`](https://docs.rs/roxmltree/0.15.1/roxmltree/struct.Node.html) (behind a feature gate called `simplecss`)?

## Notes

As stated in its README, "[`simplecss`] is not a browser-grade CSS parser. If you need one, use [cssparser](https://crates.io/crates/cssparser) + [selectors](https://crates.io/crates/selectors)."
If you agree with my request now and if, at some point in the future, I would implement [`selectors::Element`](https://docs.rs/selectors/0.23.0/selectors/trait.Element.html) on `roxmltree::Node`, would you consider adding it in a similar fashion?

**Comment by RazrFalcon** [comment]
I think plugin it manually is the way to go. There is no reason to have it integrated into roxmltree, mainly because there is no integration needed to begin with.

I want to keep this crate as simple as possible and CSS is a very big dependency (simplecss isn't, but it's very limited). And XPath is a yet another rabbit hole I have no plants going into.
