### ISSUE TITLE
Less than usefull Debug output for Element

### ISSUE THREAD

**Issue by kaj** [RazrFalcon/roxmltree#87]
From roxmltree 0.15 to 0.16, the Debug output for `Element` changed from including the element name, attributes and namespaces to something similar but with an added virtual `doc` attribute including debug info for the entire document.  This changes diagnostic output in my program from a line of easy-to-digest text to thousands of not very comprehensible lines (my input xml in an example is 750 lines, which translates to 4559 lines (235 kB) out error message).

Is it possible to change this behaviour from code using roxmltree?  Would you accept a patch for skipping the `doc` virtual attribute in Debug formatting?

**Comment by RazrFalcon** [comment]
Are you sure? roxmltree does not have an `Element` type to begin with and the `Node` one has [a proper, custom debug](https://github.com/RazrFalcon/roxmltree/blob/b81ec71fb5496ddd671d683b33f2302cdf9ae0ba/src/lib.rs#L1292).

**Comment by RazrFalcon** [comment]
Oh, I see. We have to update `Attributes` and `Namespaces` iterators formatting. Will take a look.

**Comment by kaj** [comment]
Yes, it seems to be `Attributes` for `Node` of `NodeKind::Element` that contains the document.  So a custom debug for `Attributes` would probably help.
