### ISSUE TITLE
Dealing with malformed documents

### ISSUE THREAD

**Issue by kavika13** [RazrFalcon/roxmltree#97]
I have some existing data that I want to parse that is malformed. It is part of an existing shipped game, and mods have been based off this data (including copy/pasting and editing the files), so doing the mass-updates to this data would be kinda painful, from a community-support standpoint.

Specifically, it has:

- `<?xml version="2.0" ?>` (non-existent XML version number)
- Multiple root nodes

There are xml parsers (at least in other languages) that are capable of being bent to parse these. The game (written in C++) is using one such parser.
I'm wondering if it would be good to add non-default options to support these types of errors?

Is there already an existing way to continue trying to parse even when an error like this is encountered?

If not, do you know if there's other Rust XML parsers that might be better at this sort of thing?
Would it make sense to use `RazrFalcon/xmlparser` directly, and would it support malformed documents like this?
I picked this particular parser due to the focus on performance (and secondarily, correctness). But I could consider switching if there's a better option for my use case.

If adding some optional flexibility things like this would be good, I might consider submitting some PRs for these workarounds in specific. Let me know if that would be welcome or would expedite this request.

**Comment by RazrFalcon** [comment]
I think a fork is the only option. The correctness part is very important to roxmltree. And I don't think it would be possible to add multi-root support at all.

roxmltree has a very specific use case and focus. There are no plans on adding any new features beyond one already exist.

**Comment by kavika13** [comment]
For what it's worth, the changes are very small and few. xmlparser already exposes a parameter (allow_fragments) that somewhat solves the multiple root documents problem. It's just not exposed on roxmltree. The caveat is that with that hack in place, to get all the elements, you need to enumerate descendants on the document instead of on the root.

I suppose the ease of implementation just makes it easier to fork.

I understand not wanting to support use cases of bending the rules, since that might open up a can of worms maintenance and scope wise.

**Comment by RazrFalcon** [comment]
Yes, this is all about maintainability.
